We have chosen 4 datasets each mainly focused are catergorization of mpesa transactions to understand what is an expense and income

The expected variable for each dataset varies as each is supposed to train a different aspect:

budget_data.csv- it is mainly focused for simple catergorization using the {catergory} column

expense_data_1.csv- the expected variable here is {Sub catergory},{Income/Expense},{Account}

Mpsea_synthetic.csv-Although it is supposed to be used for fraud detection the balance before and after to catergorize expense and income seems indispencble to the training model thus we have decided to use it 

Mpesa_statement.ods-The expected variable output for this is the {details} to training reading of mpesa transaction messages

1. The chosen dataset is the mpesa_statement as it has the most suitable data for training the AI for catergorization as instead of plain clear text it has to go through messages

In [1]:
import pandas as pd

df = pd.read_excel('Data/mpesa_statement.ods', engine='odf')

df.head()

,Receipt No.,Completion Time,Details,Transaction Status,Paid In,Withdrawn,Balance
0,REF8MUC88I,2023-05-15 20:19:22,Customer Transfer Fuliza MPesato - 07******212...,Completed,NaN,-50,0
1,REF8MUC88I,2023-05-15 20:19:22,OverDraft of Credit Party,Completed,50,NaN,50
2,REF9MU2IWF,2023-05-15 20:17:21,Merchant Payment Fuliza M-Pesato 7384394 - DAM...,Completed,NaN,-30,0
3,REF9MU2IWF,2023-05-15 20:17:21,OverDraft of Credit Party,Completed,30,NaN,30
4,REF7MT5G7N,2023-05-15 20:10:35,Customer Transfer Fuliza MPesato - 2547******5...,Completed,NaN,-10,0

2. How many rows and columns are in the dataset?

There are 7 columns in the dataset and around 3970 rows of data

In [2]:
rows, cols = df.shape
print(f"a. Rows: {rows}, Columns: {cols}")

a. Rows: 3967, Columns: 7

3. What are the datatypes found in the dataset?

In [3]:
print("b. Column Data Types:")
print(df.dtypes)

b. Column Data Types:
Receipt No.              str
Completion Time          str
Details                  str
Transaction Status       str
Paid In               object
Withdrawn             object
Balance               object
dtype: object

4. Is the dataset complete?

No, the dataset is an pure extraction of mpesa statement print meaning some cells are filled with different data like USSD codes and statement verification and ssafaricom tags

In [4]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print("c. Completeness check:")
print("Dataset is complete." if missing.empty else missing)

c. Completeness check:
Receipt No.             82
Completion Time        163
Details                245
Transaction Status     244
Paid In               2446
Withdrawn             1677
Balance                244
dtype: int64

5. Slice out the first 15 rows and last 20 rows and merge them into a new
dataframe titled “df_sample”. Display this new dataframe.

In [5]:
df_sample = pd.concat([df.head(15), df.tail(20)])
print("d. Displaying merged df_sample:")
display(df_sample)

d. Displaying merged df_sample:

,Receipt No.,Completion Time,Details,Transaction Status,Paid In,Withdrawn,Balance
0,REF8MUC88I,2023-05-15 20:19:22,Customer Transfer Fuliza MPesato - 07******212...,Completed,NaN,-50,0
1,REF8MUC88I,2023-05-15 20:19:22,OverDraft of Credit Party,Completed,50,NaN,50
2,REF9MU2IWF,2023-05-15 20:17:21,Merchant Payment Fuliza M-Pesato 7384394 - DAM...,Completed,NaN,-30,0
3,REF9MU2IWF,2023-05-15 20:17:21,OverDraft of Credit Party,Completed,30,NaN,30
4,REF7MT5G7N,2023-05-15 20:10:35,Customer Transfer Fuliza MPesato - 2547******5...,Completed,NaN,-10,0
5,REF7MT5G7N,2023-05-15 20:10:35,OverDraft of Credit Party,Completed,10,NaN,10
6,REF6MSH7KM,2023-05-15 20:05:47,Merchant Payment Fuliza M-Pesato 671957 - FISH...,Completed,NaN,-70,0
7,REF6MSH7KM,2023-05-15 20:05:47,OverDraft of Credit Party,Completed,70,NaN,70
8,REF5MQQC5T,2023-05-15 19:53:32,OD Loan Repayment to 232323 -M-PESA Overdraw,Completed,NaN,-150,0
9,REF0MQQ2C2,2023-05-15 19:53:32,Funds received from -07******440 diana mugwe,Completed,150,NaN,150
10,REF3MPEEH1,2023-05-15 19:44:50,OD Loan Repayment to 232323 -M-PESA Overdraw,Completed,NaN,-300,0
11,REF0MPE7MK,2023-05-15 19:44:44,Funds received from -2547******646 CAROLINEWAN...,Completed,300,NaN,300
12,REF2MGGIT6,2023-05-15 18:49:43,Merchant Payment Fuliza M-Pesato 7066744 - BRE...,Completed,NaN,-20,0
13,REF2MGGIT6,2023-05-15 18:49:43,OverDraft of Credit Party,Completed,20,NaN,20
14,REF1MB56GL,2023-05-15 18:13:05,OD Loan Repayment to 232323 -M-PESA Overdraw,Completed,NaN,-20,0
3947,QEH569D7GJ,2022-05-17 18:04:16,OverDraft of Credit Party,Completed,206,NaN,206
3948,QEH2691DNK,2022-05-17 18:00:40,OD Loan Repayment to 232323 -M-PESA Overdraw,Completed,NaN,-330,0
3949,QEH8691O6W,2022-05-17 18:00:39,Funds received from -07******874 POLEEN MWANGI,Completed,330,NaN,330
3950,QEH35NHIUF,2022-05-17 12:53:03,Customer Transfer Fuliza MPesato - 2547******5...,Completed,NaN,-10,0
3951,QEH35NHIUF,2022-05-17 12:53:03,OverDraft of Credit Party,Completed,10,NaN,10
3952,QEH05B8KLU,2022-05-17 09:35:34,Customer Transfer Fuliza MPesato - 2547******0...,Completed,NaN,-35,0
3953,QEH05B8KLU,2022-05-17 09:35:34,OverDraft of Credit Party,Completed,35,NaN,35
3954,QEG84UHWT6,2022-05-16 20:59:37,OD Loan Repayment to 232323 -M-PESA Overdraw,Completed,NaN,-20,0
3955,QEG14UI9FZ,2022-05-16 20:59:37,Funds received from -2547******867 collins kip...,Completed,20,NaN,20
3956,QEG64I7M28,2022-05-16 18:54:44,Customer Transfer of FundsCharge,Completed,NaN,-6,0
3957,QEG64I7M28,2022-05-16 18:54:44,Customer Transfer Fuliza MPesato - 07******245...,Completed,NaN,-113,6
3958,QEG64I7M28,2022-05-16 18:54:44,OverDraft of Credit Party,Completed,119,NaN,119
3959,QEG64CBRDO,2022-05-16 17:54:30,Merchant Payment Fuliza M-Pesato 7245466 - DEN...,Completed,NaN,-50,0
3960,QEG64CBRDO,2022-05-16 17:54:30,OverDraft of Credit Party,Completed,50,NaN,50
3961,QEG13WW71B,2022-05-16 14:19:25,Customer Transfer of FundsCharge,Completed,NaN,-12,0
3962,QEG13WW71B,2022-05-16 14:19:25,Customer Transfer Fuliza MPesato - 2547******6...,Completed,NaN,-850,12
3963,QEG13WW71B,2022-05-16 14:19:25,OverDraft of Credit Party,Completed,292.37,NaN,862
3964,Receipt No.,Completion Time,Details,Transaction Status,Paid In,Withdrawn,Balance
3965,QEG03RDEQM,2022-05-16 12:52:30,OD Loan Repayment to 232323 -M-PESA Overdraw,Completed,NaN,-480.37,569.63
3966,QEG23RDHRU,2022-05-16 12:52:29,Funds received from -07******245 daniel njeri,Completed,1050,NaN,1050